// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqXsbMtP_vrvl0JF7ch55yLHtkLgZG030',
    appId: '1:1056481040552:web:07fcea5b713ff3b0a14a9d',
    messagingSenderId: '1056481040552',
    projectId: 'noteapp-ba88f',
    authDomain: 'noteapp-ba88f.firebaseapp.com',
    storageBucket: 'noteapp-ba88f.firebasestorage.app',
    measurementId: 'G-NRZX7XGP3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi2cpzE9vWdE2qjBEFjv9dLrlmwrjHPXQ',
    appId: '1:1056481040552:android:8c7de3e5c433d7a7a14a9d',
    messagingSenderId: '1056481040552',
    projectId: 'noteapp-ba88f',
    storageBucket: 'noteapp-ba88f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGDRzl4PN61UouX2Dw0GZZsfsO9M9viUY',
    appId: '1:1056481040552:ios:5c702dd731d3d4f7a14a9d',
    messagingSenderId: '1056481040552',
    projectId: 'noteapp-ba88f',
    storageBucket: 'noteapp-ba88f.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGDRzl4PN61UouX2Dw0GZZsfsO9M9viUY',
    appId: '1:1056481040552:ios:5c702dd731d3d4f7a14a9d',
    messagingSenderId: '1056481040552',
    projectId: 'noteapp-ba88f',
    storageBucket: 'noteapp-ba88f.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqXsbMtP_vrvl0JF7ch55yLHtkLgZG030',
    appId: '1:1056481040552:web:d4dce08a4037c054a14a9d',
    messagingSenderId: '1056481040552',
    projectId: 'noteapp-ba88f',
    authDomain: 'noteapp-ba88f.firebaseapp.com',
    storageBucket: 'noteapp-ba88f.firebasestorage.app',
    measurementId: 'G-VJWEV3PWP4',
  );
}
